// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/azureeventhub (interfaces: AzureEventHubClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/azureeventhub/mock_azureeventhub.go -package mock_azureeventhub github.com/rudderlabs/rudder-server/services/streammanager/azureeventhub AzureEventHubClient
//

// Package mock_azureeventhub is a generated GoMock package.
package mock_azureeventhub

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAzureEventHubClient is a mock of AzureEventHubClient interface.
type MockAzureEventHubClient struct {
	ctrl     *gomock.Controller
	recorder *MockAzureEventHubClientMockRecorder
	isgomock struct{}
}

// MockAzureEventHubClientMockRecorder is the mock recorder for MockAzureEventHubClient.
type MockAzureEventHubClientMockRecorder struct {
	mock *MockAzureEventHubClient
}

// NewMockAzureEventHubClient creates a new mock instance.
func NewMockAzureEventHubClient(ctrl *gomock.Controller) *MockAzureEventHubClient {
	mock := &MockAzureEventHubClient{ctrl: ctrl}
	mock.recorder = &MockAzureEventHubClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureEventHubClient) EXPECT() *MockAzureEventHubClientMockRecorder {
	return m.recorder
}

// SendEventDataBatch mocks base method.
func (m *MockAzureEventHubClient) SendEventDataBatch(ctx context.Context, batch []byte, partitionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEventDataBatch", ctx, batch, partitionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEventDataBatch indicates an expected call of SendEventDataBatch.
func (mr *MockAzureEventHubClientMockRecorder) SendEventDataBatch(ctx, batch, partitionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEventDataBatch", reflect.TypeOf((*MockAzureEventHubClient)(nil).SendEventDataBatch), ctx, batch, partitionKey)
}
