package types

// FunctionRequest represents an incoming HTTP request to be processed by a Source Function.
// Source Functions receive this request and produce events via the onRequest handler (E-015).
// The request carries the raw HTTP method, URL, headers, body, query parameters, and any
// function-level settings configured through the Functions management API (E-018/E-019).
type FunctionRequest struct {
	// Method is the HTTP method of the incoming webhook request (e.g., GET, POST, PUT).
	Method string `json:"method"`
	// URL is the full request URL including path and query string.
	URL string `json:"url"`
	// Headers contains the HTTP request headers as key-value pairs.
	Headers map[string]string `json:"headers"`
	// Body is the raw request body bytes.
	Body []byte `json:"body"`
	// QueryParams contains parsed URL query parameters as key-value pairs.
	QueryParams map[string]string `json:"queryParams"`
	// Settings contains function-level configuration and secrets resolved at runtime.
	// These are managed through the Functions secrets management API (E-019).
	Settings map[string]any `json:"settings"`
}

// FunctionResponse represents the result of executing a Source Function's onRequest handler.
// It contains the events generated by the function and execution metadata (E-015).
// The generated events are injected into the normal pipeline processing flow through
// the Gateway, following the same path as SDK-originated events.
type FunctionResponse struct {
	// Events contains the events generated by the Source Function's onRequest handler.
	// Each event follows the standard RudderStack event schema (track, identify, group, etc.).
	Events []SingularEventT `json:"events"`
	// StatusCode is the HTTP status code to return to the webhook caller.
	// A 200 indicates successful processing; non-200 codes indicate function errors.
	StatusCode int `json:"statusCode"`
	// Error contains an error message if the function execution failed.
	// Empty string indicates successful execution.
	Error string `json:"error,omitempty"`
}
