// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/redisstream (interfaces: RedisStreamClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/services/streammanager/redisstream/mock_redisstream.go -package mock_redisstream github.com/rudderlabs/rudder-server/services/streammanager/redisstream RedisStreamClient
//

// Package mock_redisstream is a generated GoMock package.
package mock_redisstream

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisStreamClient is a mock of RedisStreamClient interface.
type MockRedisStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisStreamClientMockRecorder
	isgomock struct{}
}

// MockRedisStreamClientMockRecorder is the mock recorder for MockRedisStreamClient.
type MockRedisStreamClientMockRecorder struct {
	mock *MockRedisStreamClient
}

// NewMockRedisStreamClient creates a new mock instance.
func NewMockRedisStreamClient(ctrl *gomock.Controller) *MockRedisStreamClient {
	mock := &MockRedisStreamClient{ctrl: ctrl}
	mock.recorder = &MockRedisStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisStreamClient) EXPECT() *MockRedisStreamClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisStreamClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisStreamClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisStreamClient)(nil).Close))
}

// XAdd mocks base method.
func (m *MockRedisStreamClient) XAdd(ctx context.Context, stream string, values map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XAdd", ctx, stream, values)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XAdd indicates an expected call of XAdd.
func (mr *MockRedisStreamClientMockRecorder) XAdd(ctx, stream, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAdd", reflect.TypeOf((*MockRedisStreamClient)(nil).XAdd), ctx, stream, values)
}
