// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/identity/profiles.proto

package identityproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProfilesService_GetProfile_FullMethodName            = "/identity.ProfilesService/GetProfile"
	ProfilesService_GetProfileTraits_FullMethodName      = "/identity.ProfilesService/GetProfileTraits"
	ProfilesService_GetProfileEvents_FullMethodName      = "/identity.ProfilesService/GetProfileEvents"
	ProfilesService_GetProfileExternalIds_FullMethodName = "/identity.ProfilesService/GetProfileExternalIds"
	ProfilesService_GetProfileMetadata_FullMethodName    = "/identity.ProfilesService/GetProfileMetadata"
)

// ProfilesServiceClient is the client API for ProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfilesServiceClient interface {
	// E-027: Get a unified profile by identifier.
	// Resolves a profile using any supported identifier type (user_id, email, anonymous_id, etc.)
	// and optionally includes sub-resources (traits, external_ids, events, metadata).
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	// E-027: Get profile traits (key-value attributes).
	// Returns the merged trait map for a resolved profile, with pagination support.
	GetProfileTraits(ctx context.Context, in *GetProfileTraitsRequest, opts ...grpc.CallOption) (*ProfileTraits, error)
	// E-027: Get profile events (historical event stream).
	// Returns events associated with a profile, filterable by event type and time range.
	GetProfileEvents(ctx context.Context, in *GetProfileEventsRequest, opts ...grpc.CallOption) (*ProfileEvents, error)
	// E-027: Get profile external IDs (cross-device/cross-platform identifiers).
	// Returns all external identifiers linked to a profile through identity resolution.
	// Supports 12+ identifier types per E-028.
	GetProfileExternalIds(ctx context.Context, in *GetProfileExternalIdsRequest, opts ...grpc.CallOption) (*ProfileExternalIds, error)
	// E-027: Get profile metadata (merge history, timestamps).
	// Returns merge count, first/last seen timestamps, and workspace context.
	GetProfileMetadata(ctx context.Context, in *GetProfileMetadataRequest, opts ...grpc.CallOption) (*ProfileMetadata, error)
}

type profilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilesServiceClient(cc grpc.ClientConnInterface) ProfilesServiceClient {
	return &profilesServiceClient{cc}
}

func (c *profilesServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, ProfilesService_GetProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) GetProfileTraits(ctx context.Context, in *GetProfileTraitsRequest, opts ...grpc.CallOption) (*ProfileTraits, error) {
	out := new(ProfileTraits)
	err := c.cc.Invoke(ctx, ProfilesService_GetProfileTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) GetProfileEvents(ctx context.Context, in *GetProfileEventsRequest, opts ...grpc.CallOption) (*ProfileEvents, error) {
	out := new(ProfileEvents)
	err := c.cc.Invoke(ctx, ProfilesService_GetProfileEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) GetProfileExternalIds(ctx context.Context, in *GetProfileExternalIdsRequest, opts ...grpc.CallOption) (*ProfileExternalIds, error) {
	out := new(ProfileExternalIds)
	err := c.cc.Invoke(ctx, ProfilesService_GetProfileExternalIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesServiceClient) GetProfileMetadata(ctx context.Context, in *GetProfileMetadataRequest, opts ...grpc.CallOption) (*ProfileMetadata, error) {
	out := new(ProfileMetadata)
	err := c.cc.Invoke(ctx, ProfilesService_GetProfileMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServiceServer is the server API for ProfilesService service.
// All implementations must embed UnimplementedProfilesServiceServer
// for forward compatibility
type ProfilesServiceServer interface {
	// E-027: Get a unified profile by identifier.
	// Resolves a profile using any supported identifier type (user_id, email, anonymous_id, etc.)
	// and optionally includes sub-resources (traits, external_ids, events, metadata).
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	// E-027: Get profile traits (key-value attributes).
	// Returns the merged trait map for a resolved profile, with pagination support.
	GetProfileTraits(context.Context, *GetProfileTraitsRequest) (*ProfileTraits, error)
	// E-027: Get profile events (historical event stream).
	// Returns events associated with a profile, filterable by event type and time range.
	GetProfileEvents(context.Context, *GetProfileEventsRequest) (*ProfileEvents, error)
	// E-027: Get profile external IDs (cross-device/cross-platform identifiers).
	// Returns all external identifiers linked to a profile through identity resolution.
	// Supports 12+ identifier types per E-028.
	GetProfileExternalIds(context.Context, *GetProfileExternalIdsRequest) (*ProfileExternalIds, error)
	// E-027: Get profile metadata (merge history, timestamps).
	// Returns merge count, first/last seen timestamps, and workspace context.
	GetProfileMetadata(context.Context, *GetProfileMetadataRequest) (*ProfileMetadata, error)
	mustEmbedUnimplementedProfilesServiceServer()
}

// UnimplementedProfilesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProfilesServiceServer struct {
}

func (UnimplementedProfilesServiceServer) GetProfile(context.Context, *GetProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedProfilesServiceServer) GetProfileTraits(context.Context, *GetProfileTraitsRequest) (*ProfileTraits, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileTraits not implemented")
}
func (UnimplementedProfilesServiceServer) GetProfileEvents(context.Context, *GetProfileEventsRequest) (*ProfileEvents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileEvents not implemented")
}
func (UnimplementedProfilesServiceServer) GetProfileExternalIds(context.Context, *GetProfileExternalIdsRequest) (*ProfileExternalIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileExternalIds not implemented")
}
func (UnimplementedProfilesServiceServer) GetProfileMetadata(context.Context, *GetProfileMetadataRequest) (*ProfileMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileMetadata not implemented")
}
func (UnimplementedProfilesServiceServer) mustEmbedUnimplementedProfilesServiceServer() {}

// UnsafeProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfilesServiceServer will
// result in compilation errors.
type UnsafeProfilesServiceServer interface {
	mustEmbedUnimplementedProfilesServiceServer()
}

func RegisterProfilesServiceServer(s grpc.ServiceRegistrar, srv ProfilesServiceServer) {
	s.RegisterService(&ProfilesService_ServiceDesc, srv)
}

func _ProfilesService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_GetProfileTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetProfileTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetProfileTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetProfileTraits(ctx, req.(*GetProfileTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_GetProfileEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetProfileEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetProfileEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetProfileEvents(ctx, req.(*GetProfileEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_GetProfileExternalIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileExternalIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetProfileExternalIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetProfileExternalIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetProfileExternalIds(ctx, req.(*GetProfileExternalIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesService_GetProfileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServiceServer).GetProfileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesService_GetProfileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServiceServer).GetProfileMetadata(ctx, req.(*GetProfileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfilesService_ServiceDesc is the grpc.ServiceDesc for ProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.ProfilesService",
	HandlerType: (*ProfilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _ProfilesService_GetProfile_Handler,
		},
		{
			MethodName: "GetProfileTraits",
			Handler:    _ProfilesService_GetProfileTraits_Handler,
		},
		{
			MethodName: "GetProfileEvents",
			Handler:    _ProfilesService_GetProfileEvents_Handler,
		},
		{
			MethodName: "GetProfileExternalIds",
			Handler:    _ProfilesService_GetProfileExternalIds_Handler,
		},
		{
			MethodName: "GetProfileMetadata",
			Handler:    _ProfilesService_GetProfileMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identity/profiles.proto",
}
