// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/streammanager/amazonmsk (interfaces: MSKClient)
//
// Generated by this command:
//
//	mockgen -package amazonmsk -destination=services/streammanager/amazonmsk/mock_msk_test.go github.com/rudderlabs/rudder-server/services/streammanager/amazonmsk MSKClient
//

// Package amazonmsk is a generated GoMock package.
package amazonmsk

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMSKClient is a mock of MSKClient interface.
type MockMSKClient struct {
	ctrl     *gomock.Controller
	recorder *MockMSKClientMockRecorder
	isgomock struct{}
}

// MockMSKClientMockRecorder is the mock recorder for MockMSKClient.
type MockMSKClientMockRecorder struct {
	mock *MockMSKClient
}

// NewMockMSKClient creates a new mock instance.
func NewMockMSKClient(ctrl *gomock.Controller) *MockMSKClient {
	mock := &MockMSKClient{ctrl: ctrl}
	mock.recorder = &MockMSKClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMSKClient) EXPECT() *MockMSKClientMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMSKClient) SendMessage(ctx context.Context, msg *MSKMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMSKClientMockRecorder) SendMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMSKClient)(nil).SendMessage), ctx, msg)
}
