// Package runtime — source_functions.go
//
// Implements Source Functions (Sprint 4-6, Epic E-015): custom webhook
// ingestion via the onRequest(request, settings) handler pattern. Source
// Functions receive an HTTP webhook request and transform it into one or more
// RudderStack events (track, identify, group, page, screen calls).
//
// Architecture:
//
//	Gateway webhook → ExecuteSourceFunction → Transformer /v1/functions/source
//	                                              → SourceFunctionResult.Events
//	                                              → injected back into Gateway pipeline
//
// The execution is delegated to the external Transformer service via HTTP POST,
// following the communication pattern established by
// processor/internal/transformer/user_transformer/user_transformer.go.
//
// Reference: refs/segment-docs/src/connections/functions/source-functions.md
package runtime

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/rudderlabs/rudder-go-kit/jsonrs"
	"github.com/rudderlabs/rudder-go-kit/logger"
	"github.com/rudderlabs/rudder-go-kit/stats"
	obskit "github.com/rudderlabs/rudder-observability-kit/go/labels"
)

// ---------------------------------------------------------------------------
// Source Function types
// ---------------------------------------------------------------------------

// SourceFunctionRequest represents the incoming HTTP webhook request that is
// passed to a Source Function's onRequest handler. This mirrors the Segment
// Source Functions contract where the request object contains the raw HTTP
// method, URL, headers, body, and query parameters.
//
// All fields faithfully represent an HTTP request:
//   - Method, URL: standard HTTP request-line components
//   - Headers, QueryParams: multi-valued maps matching Go's http.Header type
//   - Body: raw JSON preserved as json.RawMessage to avoid unnecessary parsing
//
// Body may be nil for requests without a body (e.g. GET webhooks). Source
// Function handlers must tolerate a nil body per the Segment contract and
// AAP requirements.
type SourceFunctionRequest struct {
	// Method is the HTTP method of the incoming webhook request
	// (GET, POST, PUT, DELETE, PATCH, etc.).
	Method string `json:"method"`

	// URL is the request URL path of the incoming webhook.
	URL string `json:"url"`

	// Headers contains the HTTP headers from the incoming webhook request.
	// Headers are multi-valued, matching the Go http.Header type convention.
	Headers map[string][]string `json:"headers"`

	// Body is the raw request body as JSON. It may be nil for GET requests
	// or other requests without a body, which is a valid scenario for Source
	// Functions that handle GET-based webhooks or health-check pings.
	Body json.RawMessage `json:"body"`

	// QueryParams contains the URL query parameters from the incoming webhook.
	// Query parameters are multi-valued, matching Go's url.Values convention.
	QueryParams map[string][]string `json:"queryParams"`
}

// SourceFunctionResult represents the output of a Source Function execution.
// The Events field contains an array of RudderStack events generated by the
// onRequest handler (track, identify, group, page, screen calls).
//
// Each event in the Events array is a complete RudderStack event JSON with
// "type", "userId"/"anonymousId", and event-specific fields. These events
// are injected into the Gateway's event pipeline as if they came from SDK
// calls.
//
// An empty Events slice is valid — the Source Function may choose not to
// produce any events for a given request (e.g. health-check pings or
// duplicate detection).
type SourceFunctionResult struct {
	// Events contains the array of RudderStack events generated by the
	// Source Function's onRequest handler. Each element is a raw JSON
	// RudderStack event (track, identify, group, page, screen).
	Events []json.RawMessage `json:"events"`
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// sourceRequestHandler is the fixed handler name for Source Functions. Per the
// Segment Source Functions contract, the only handler is "onRequest" — unlike
// Destination/Insert Functions which dispatch to typed handlers (onTrack,
// onIdentify, etc.).
const sourceRequestHandler = "onRequest"

// ---------------------------------------------------------------------------
// ExecuteSourceFunction
// ---------------------------------------------------------------------------

// ExecuteSourceFunction executes a Source Function's onRequest handler by
// sending the HTTP webhook request to the Transformer service and returning
// the generated RudderStack events.
//
// The Segment Source Functions contract:
//   - onRequest(request, settings) receives the HTTP request object
//   - Returns an array of event objects (track, identify, group, page, screen)
//   - Each returned event is injected into the RudderStack pipeline as if it
//     came from an SDK
//
// Source Functions are invoked from gateway/handle_http_functions.go when
// webhooks arrive at /v1/functions/source. The returned events from
// SourceFunctionResult.Events are injected into the Gateway's event pipeline.
//
// This method communicates with the external Transformer service via HTTP POST,
// following the same pattern established in
// processor/internal/transformer/user_transformer/user_transformer.go.
//
// Reference: refs/segment-docs/src/connections/functions/source-functions.md
func (e *Engine) ExecuteSourceFunction(
	ctx context.Context,
	fn *FunctionDef,
	request *SourceFunctionRequest,
	settings map[string]string,
) (*SourceFunctionResult, error) {
	// -----------------------------------------------------------------------
	// Phase 1: Input validation
	// -----------------------------------------------------------------------

	if fn == nil {
		return nil, fmt.Errorf("function definition is required")
	}
	if request == nil {
		return nil, &InvalidEventPayload{Message: "source function request is required"}
	}
	if fn.Type != FunctionTypeSource {
		return nil, &ValidationError{
			Message: fmt.Sprintf("function type must be source, got: %s", fn.Type),
		}
	}

	// -----------------------------------------------------------------------
	// Phase 2: Prepare logging and timing
	// -----------------------------------------------------------------------

	log := e.log.Child("source_functions")
	start := time.Now()

	// Extract Content-Type for debug logging (may be empty for GET requests).
	contentType := extractContentType(request.Headers)

	log.Debugn("Executing source function",
		logger.NewStringField("functionId", fn.ID),
		logger.NewStringField("method", request.Method),
		logger.NewStringField("url", request.URL),
		logger.NewStringField("contentType", contentType),
	)

	// -----------------------------------------------------------------------
	// Phase 3: Build Transformer service request payload
	// -----------------------------------------------------------------------

	// Serialize the SourceFunctionRequest into json.RawMessage so it can be
	// embedded in the transformerRequest.Request field. The Transformer
	// service receives the raw HTTP request as a JSON object.
	requestPayload, err := jsonrs.Marshal(request)
	if err != nil {
		log.Errorn("Failed to marshal source function request",
			logger.NewStringField("functionId", fn.ID),
			obskit.Error(err),
		)
		recordSourceError(e.statsFactory, fn.ID, "marshal_error")
		return nil, fmt.Errorf("marshaling source function request: %w", err)
	}

	// Merge function-level settings with call-level settings. Call-level
	// settings take precedence so that callers can override per invocation,
	// matching the same merge pattern used in Engine.Execute.
	mergedSettings := mergeSettings(fn.Settings, settings)

	// Build the Transformer request payload. Source Functions always use the
	// "onRequest" handler and carry the HTTP request in the Request field
	// (as opposed to Destination/Insert Functions which use the Event field).
	tfReq := transformerRequest{
		FunctionID:  fn.ID,
		WorkspaceID: fn.WorkspaceID,
		Code:        fn.Code,
		Version:     fn.Version,
		Handler:     sourceRequestHandler,
		Request:     json.RawMessage(requestPayload),
		Settings:    mergedSettings,
	}

	// -----------------------------------------------------------------------
	// Phase 4: POST to Transformer service
	// -----------------------------------------------------------------------

	// Reuse the Engine's shared postToTransformer helper to eliminate
	// duplicated HTTP marshaling / POST / status-check logic. The helper
	// handles request marshaling, Content-Type header, round-trip metrics,
	// response body reading, and non-200 error conversion in one call.
	respBody, err := e.postToTransformer(ctx, sourceEndpoint, &tfReq)
	if err != nil {
		log.Errorn("Source function transformer request failed",
			logger.NewStringField("functionId", fn.ID),
			obskit.Error(err),
		)
		recordSourceError(e.statsFactory, fn.ID, "transformer_error")
		return nil, fmt.Errorf("source function transformer call: %w", err)
	}

	// Record the Source-Function-specific execution time (end-to-end from
	// the start of this method, complementing the generic transformer
	// round-trip metric emitted by postToTransformer).
	elapsed := time.Since(start)
	e.statsFactory.NewTaggedStat(
		"functions_source_execution_time",
		stats.TimerType,
		stats.Tags{"function_id": fn.ID},
	).SendTiming(elapsed)

	// -----------------------------------------------------------------------
	// Phase 5: Parse Transformer response
	// -----------------------------------------------------------------------

	var tfResp transformerResponse
	if err := jsonrs.Unmarshal(respBody, &tfResp); err != nil {
		log.Errorn("Failed to unmarshal source function transformer response",
			logger.NewStringField("functionId", fn.ID),
			obskit.Error(err),
		)
		recordSourceError(e.statsFactory, fn.ID, "unmarshal_error")
		return nil, fmt.Errorf("unmarshaling source function transformer response: %w", err)
	}

	// If the Transformer returned a top-level error, map it to a typed Go
	// error from errors.go (EventNotSupported, InvalidEventPayload,
	// ValidationError, RetryError, DropEvent).
	if tfResp.Error != nil && tfResp.Error.Type != "" {
		mappedErr := mapFunctionError(tfResp.Error)
		errType := classifySourceError(mappedErr)
		log.Errorn("Source function execution returned error",
			logger.NewStringField("functionId", fn.ID),
			logger.NewStringField("errorType", tfResp.Error.Type),
			logger.NewStringField("errorMessage", tfResp.Error.Message),
		)
		recordSourceError(e.statsFactory, fn.ID, errType)
		return nil, mappedErr
	}

	// -----------------------------------------------------------------------
	// Phase 6: Build result and record metrics
	// -----------------------------------------------------------------------

	result := &SourceFunctionResult{
		Events: tfResp.Events,
	}

	eventCount := len(result.Events)
	if eventCount == 0 {
		// Source function produced no events — this is valid (e.g. health-check
		// pings, duplicate detection) but worth tracking for observability.
		e.statsFactory.NewTaggedStat(
			"functions_source_empty_results",
			stats.CountType,
			stats.Tags{"function_id": fn.ID},
		).Increment()

		log.Debugn("Source function produced no events",
			logger.NewStringField("functionId", fn.ID),
		)
	} else {
		// Record the number of events generated by the source function.
		e.statsFactory.NewTaggedStat(
			"functions_source_events_generated",
			stats.CountType,
			stats.Tags{"function_id": fn.ID},
		).Count(eventCount)

		log.Debugn("Source function produced events",
			logger.NewStringField("functionId", fn.ID),
			logger.NewIntField("eventCount", int64(eventCount)),
		)
	}

	return result, nil
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// extractContentType retrieves the Content-Type header value from a
// multi-valued header map. Returns an empty string if the header is not
// present or the map is nil. This is used for debug-level logging when
// a source function execution is initiated.
func extractContentType(headers map[string][]string) string {
	if headers == nil {
		return ""
	}
	// Check the standard capitalisation first (most common case).
	if ct, ok := headers["Content-Type"]; ok && len(ct) > 0 {
		return ct[0]
	}
	// Fall back to case-insensitive search for robustness.
	for k, v := range headers {
		if len(v) > 0 && (k == "content-type" || k == "CONTENT-TYPE") {
			return v[0]
		}
	}
	return ""
}

// recordSourceError increments the source function error counter with the
// given error type tag. This is a small helper to keep the main function body
// readable while ensuring consistent metric names and tag keys.
func recordSourceError(statsFactory stats.Stats, functionID, errorType string) {
	statsFactory.NewTaggedStat(
		"functions_source_errors",
		stats.CountType,
		stats.Tags{"function_id": functionID, "error_type": errorType},
	).Increment()
}

// classifySourceError returns a string classification for a function error,
// used for metrics tagging. It checks for the five typed errors defined in
// errors.go using direct type assertions. The returned string is used as a
// tag value for the "error_type" dimension in metrics.
func classifySourceError(err error) string {
	if err == nil {
		return "none"
	}
	switch err.(type) {
	case *RetryError:
		return "retry"
	case *DropEvent:
		return "drop"
	case *EventNotSupported:
		return "event_not_supported"
	case *InvalidEventPayload:
		return "invalid_payload"
	case *ValidationError:
		return "validation"
	default:
		return "unknown"
	}
}
